export const ROUTE_PATHS = {
  login: '/auth/login',
  dashboard: '/dashboard',
  periods: '/periods',
  students: '/students',
  companies: '/companies',
  placements: '/placements',
  documents: '/documents',
  documentAutomation: '/document-automation',
  readiness: '/administrative-readiness',
  reports: '/reports',
  archives: '/archives',
  majors: '/majors',
  classes: '/classes',
  supervisors: '/supervisors',
  users: '/users',
  roles: '/roles',
  permissions: '/permissions',
  settings: '/settings',
  forbidden: '/403',
  notFound: '/404',
} as const
