export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  periods: '/periods',
  majors: '/majors',
  classes: '/classes',
  students: '/students',
  studentImport: '/students/import',
  companies: '/companies',
  companyContacts: '/company-contacts',
  companyMajorCapacities: (id: string) => `/companies/${id}/major-capacities`,
  supervisors: '/supervisors',
  placements: '/placements',
  placementTransfer: (id: string) => `/placements/${id}/transfer`,
  documents: '/documents',
  documentTypes: '/document-types',
  documentVerify: (id: string) => `/documents/${id}/verify`,
  documentDownload: (id: string) => `/documents/${id}/download`,
  readinessRecalculate: '/readiness/recalculate',
  readinessOverride: '/readiness/override',
  readiness: '/readiness',
  dashboard: '/reports/dashboard',
  placementReports: '/reports/placements',
  expirationReports: '/reports/expirations',
  archives: '/archives',
  users: '/users',
  userRoles: (id: string) => `/users/${id}/roles`,
  roles: '/roles',
  rolePermissions: (id: string) => `/roles/${id}/permissions`,
  permissions: '/permissions',
  automation: {
    profile: '/document-automation/profile',
    signatories: '/document-automation/signatories',
    templates: '/document-automation/templates',
    preview: '/document-automation/preview',
    generate: '/document-automation/generate',
    batches: '/document-automation/batches',
    documents: '/document-automation/documents',
    batchDownload: (id: string) =>
      `/document-automation/batches/${id}/download`,
    documentDownload: (id: string) =>
      `/document-automation/documents/${id}/download`,
  },
} as const
